import AppKit

let image = NSImage(size: NSSize(width: 1024, height: 1024))
image.lockFocus()
NSColor.clear.setFill()
NSRect(x: 0, y: 0, width: 1024, height: 1024).fill()
let base = NSBezierPath(roundedRect: NSRect(x: 64, y: 64, width: 896, height: 896), xRadius: 202, yRadius: 202)
NSColor(calibratedWhite: 0.94, alpha: 1).setFill(); base.fill()
let inset = NSBezierPath(roundedRect: NSRect(x: 89, y: 89, width: 846, height: 846), xRadius: 180, yRadius: 180)
NSColor(calibratedWhite: 0.08, alpha: 1).setFill(); inset.fill()
let bolt = NSBezierPath()
bolt.move(to: NSPoint(x: 579, y: 812))
bolt.line(to: NSPoint(x: 291, y: 477))
bolt.line(to: NSPoint(x: 471, y: 477))
bolt.line(to: NSPoint(x: 428, y: 215))
bolt.line(to: NSPoint(x: 742, y: 565))
bolt.line(to: NSPoint(x: 550, y: 565))
bolt.close()
NSColor(calibratedWhite: 0.98, alpha: 1).setFill(); bolt.fill()
NSColor(calibratedWhite: 0.55, alpha: 1).setFill()
NSBezierPath(ovalIn: NSRect(x: 729, y: 227, width: 78, height: 78)).fill()
image.unlockFocus()
let bitmap = NSBitmapImageRep(data: image.tiffRepresentation!)!
try bitmap.representation(using: .png, properties: [:])!.write(to: URL(fileURLWithPath: CommandLine.arguments[1]))
